# Generated by Django 4.2.1 on 2023-11-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_sale_invoice_invoice_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='last_registered_invoice',
            field=models.IntegerField(),
        ),
    ]
